### ISSUE TITLE
Could objects be used instead of arrays for caches?

### ISSUE THREAD

**Issue by pparke** [eduardoleao052/js-torch#19]
All of the cases where a `cache` field exists on a class in the `tensor.ts` module look like they could be converted to an object that would be easier to define types for. For example, the cache on the `Add` class has 2 elements `a` and `b` which are both either a `Tensor` or a `number` so if cache were changed to an object:

```
export class Add {
  cache?: {
    a: Tensor | number;
    b: Tensor | number;
  }

  forward(/* ... */) {
    this.cache = {a, b};
    // ...
  }

  backward(/* ... */) {
    if (typeof this.cache === "undefined") {
      throw Error("Cache is not defined.");
    }
    
    const {a, b} = this.cache;
    // ...
  }
```

doing this already turns up a type error with `broadcast` where the second parameter is typed as a `Tensor` but it should be `Tensor | number | number[] | number[][]`.

Let me know what you think. It would be an easy change to switch the caches over to objects.

**Comment by eduardoleao052** [comment]
If you think it would make the code simpler an easier to apply classes to, then it makes sense. I used Arrays because I wasn't thinking about TS originally, and using Arrays takes up a single line of code.

**Comment by eduardoleao052** [comment]
Thanks! I see your point, and agree with it! Are you planning on adding that in your current PR, or should I add it separately?

**Comment by pparke** [comment]
If I add it I would probably make a new PR just so the changes are well separated from others but I'm not able to work on it for a bit so if you'd like to do it then I won't stop you!
