### ISSUE TITLE
Code in Simple Autograd Example seems to have capitalization errors

### ISSUE THREAD

**Issue by victorsonger** [eduardoleao052/js-torch#2]
Description：
  When running the **Simple Autograd Example** in README, encounter the following error:

```
      out = torch.matmul(x, w);
                  ^
      TypeError: torch.matmul is not a function
```

Looks like **matmul** should be **matMul**

**Comment by eduardoleao052** [comment]
You are absolutely right lol. Now that you mentioned it, I chose to stick to `torch.matmul`, since its closer to Pytorch's syntax. Thank you for pointing it out!
