### ISSUE TITLE
Templates for issues 

### ISSUE THREAD

**Issue by medic-code** [eduardoleao052/js-torch#22]
Just a thought and this may be a little premature at the moment, but having a structured template for new features and bugs can be extremely useful. I see all the time issues on Open Source projects which are just lacking context, so creating templates for atleast these two options might be a good way to help provide structure and give shared understanding and appropriate context to properly evaluate them.

For an example see here https://github.com/langchain-ai/langchainjs/issues/4994

**Comment by eduardoleao052** [comment]
@medic-code  Hey, that's a really good idea! I can start doing that rn, `langchain.js`'s templates are a great starting point. Thanks for the tip!
