### ISSUE TITLE
Additional configuration

### ISSUE THREAD

**Issue by medic-code** [eduardoleao052/js-torch#7]
@eduardoleao052 Just looking through your code and have a few suggestions to include some additional libraries for config, but might be worth waiting for https://github.com/eduardoleao052/js-torch/pull/6 config to be merged first as there's a large change.

1. Prettier and ESlint - for consistent formatting and a linter 
2. Test infrastructure - Jest is popular and can generate code coverage reports
3. lint-staged -  linting before commits get added to project
4. Husky - running scripts prior to commit/push for tests 

Happy to add this in a PR for you to review but let me know how you'd like to proceed.

**Comment by eduardoleao052** [comment]
Hey! Thank you so much for the suggestion! I'm working on including Typescript, which would improve the Repo's reach a lot, but I'd like to keep other libraries to a minimum (the original idea was building it with zero libraries, to be *really* accessible to any JavaScript learner, but I guess TypeScript is a fair exception).

**Comment by pparke** [comment]
The good thing with the suggested libraries is that they would just be dev dependencies which are only used to aid development and as part of the build system and tooling so they wouldn't be included in the transpiled output. They're very standard practice for JS and TS projects and they really help make it easier to keep everything consistent and easily understood by other JS/TS developers.

**Comment by eduardoleao052** [comment]
I see! With dev tools, there's really no problem. I just want to keep required libraries for the user to a minimum.

**Comment by medic-code** [comment]
These are good points @pparke, they really do make it easier to keep consistent development and anyone using JS even beginners will almost certainly come across this when creating small or large projects.
