### ISSUE TITLE
Modules + block scoping variables 

### ISSUE THREAD

**Issue by medic-code** [eduardoleao052/js-torch#8]
I noticed in the code you're using IIFEs and var variables and wondered whether you had in mind tousing block scoping variables (let and const) and modules ? 

I know it's probably on your list to do some refactoring of torch.js but modules would allow for extracting some common functionalities out of the torch.js file. Would be happy to help start some of that.

**Comment by eduardoleao052** [comment]
Hey, thanks for looking it over, glad you like it! I'm definitely planning to refactor the code in the coming days. On that note, what exactly do you mean by *using modules to allow for extracting some common functionalities*? Thanks in advance!

**Comment by eduardoleao052** [comment]
I see, that's a good approach as well!
